// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang;

/** All Visitor */

public interface AllVisitor<R,A> extends
  lang.Absyn.Program.Visitor<R,A>,
  lang.Absyn.Stm.Visitor<R,A>,
  lang.Absyn.Item.Visitor<R,A>,
  lang.Absyn.Stm_Initialise.Visitor<R,A>,
  lang.Absyn.Stm_Declare.Visitor<R,A>,
  lang.Absyn.Stm_Assign.Visitor<R,A>,
  lang.Absyn.Stm_IncrmDecrm.Visitor<R,A>,
  lang.Absyn.Stm_Loop.Visitor<R,A>,
  lang.Absyn.If_Stm.Visitor<R,A>,
  lang.Absyn.Arg.Visitor<R,A>,
  lang.Absyn.Exp.Visitor<R,A>,
  lang.Absyn.Assign_Op.Visitor<R,A>,
  lang.Absyn.IncrmDecrm_Op.Visitor<R,A>,
  lang.Absyn.FuncType.Visitor<R,A>,
  lang.Absyn.VarType.Visitor<R,A>,
  lang.Absyn.TypeCast.Visitor<R,A>
{}
