// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang;

public class PrettyPrinter
{
  //For certain applications increasing the initial size of the buffer may improve performance.
  private static final int INITIAL_BUFFER_SIZE = 128;
  private static final int INDENT_WIDTH = 2;
  //You may wish to change the parentheses used in precedence.
  private static final String _L_PAREN = "(";
  private static final String _R_PAREN = ")";
  //You may wish to change render
  private static void render(String s)
  {
    if (s.equals("{"))
    {
       onEmptyLine();
       buf_.append(s);
       _n_ = _n_ + INDENT_WIDTH;
       buf_.append("\n");
       indent();
    }
    else if (s.equals("(") || s.equals("["))
       buf_.append(s);
    else if (s.equals(")") || s.equals("]"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals("}"))
    {
       _n_ = _n_ - INDENT_WIDTH;
       onEmptyLine();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals(","))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals(";"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals("")) {
    }
    else if (s.trim().equals(""))
    {
       backup();
       buf_.append(s);
    }
    else
    {
       buf_.append(s);
       buf_.append(" ");
    }
  }


  //  print and show methods are defined for each category.
  public static String print(lang.Absyn.Program foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Program foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.Stm foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Stm foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.Item foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Item foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.ListItem foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.ListItem foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.Stm_Initialise foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Stm_Initialise foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.Stm_Declare foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Stm_Declare foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.Stm_Assign foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Stm_Assign foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.Stm_IncrmDecrm foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Stm_IncrmDecrm foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.Stm_Loop foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Stm_Loop foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.If_Stm foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.If_Stm foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.Arg foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Arg foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.ListArg foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.ListArg foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.ListStm foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.ListStm foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.Exp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Exp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.ListIdent foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.ListIdent foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.Assign_Op foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.Assign_Op foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.IncrmDecrm_Op foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.IncrmDecrm_Op foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.ListExp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.ListExp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.FuncType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.FuncType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.VarType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.VarType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(lang.Absyn.TypeCast foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(lang.Absyn.TypeCast foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  /***   You shouldn't need to change anything beyond this point.   ***/

  private static void pp(lang.Absyn.Program foo, int _i_)
  {
    if (foo instanceof lang.Absyn.PStms _pstms)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_pstms.liststm_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.PFunctionalModeStms _pfunctionalmodestms)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("paradigm");
       render(":");
       render("functional");
       pp(_pfunctionalmodestms.liststm_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.Stm foo, int _i_)
  {
    if (foo instanceof lang.Absyn.DefFun _deffun)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("function");
       pp(_deffun.functype_, 0);
       pp(_deffun.ident_, 0);
       render("(");
       pp(_deffun.listarg_, 0);
       render(")");
       render("{");
       pp(_deffun.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.DefConstructor _defconstructor)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("constructor");
       pp(_defconstructor.ident_, 0);
       render("(");
       pp(_defconstructor.listarg_, 0);
       render(")");
       render("{");
       pp(_defconstructor.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.DefClass _defclass)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("class");
       pp(_defclass.ident_, 0);
       render("{");
       pp(_defclass.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.DefClassInherits _defclassinherits)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("class");
       pp(_defclassinherits.ident_1, 0);
       render("inherits");
       pp(_defclassinherits.ident_2, 0);
       render("{");
       pp(_defclassinherits.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.STryCatch _strycatch)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("try");
       render("{");
       pp(_strycatch.liststm_1, 0);
       render("}");
       render("catch");
       render("(");
       pp(_strycatch.ident_, 0);
       render(")");
       render("{");
       pp(_strycatch.liststm_2, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.STryCatchFinally _strycatchfinally)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("try");
       render("{");
       pp(_strycatchfinally.liststm_1, 0);
       render("}");
       render("catch");
       render("(");
       pp(_strycatchfinally.ident_, 0);
       render(")");
       render("{");
       pp(_strycatchfinally.liststm_2, 0);
       render("}");
       render("finally");
       render("{");
       pp(_strycatchfinally.liststm_3, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SPrint _sprint)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("print");
       pp(_sprint.exp_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SBreak _sbreak)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("break");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SContinue _scontinue)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("continue");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SThrow _sthrow)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("throw");
       pp(_sthrow.exp_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.InitialiseStm _initialisestm)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_initialisestm.stm_initialise_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.DeclareStm _declarestm)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_declarestm.stm_declare_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.AssignStm _assignstm)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_assignstm.stm_assign_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.LoopStm _loopstm)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_loopstm.stm_loop_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.IncrnDecrmStm _incrndecrmstm)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_incrndecrmstm.stm_incrmdecrm_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SCall _scall)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_scall.exp_, 16);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SAppend _sappend)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_sappend.ident_, 0);
       render(".");
       render("append");
       render("(");
       pp(_sappend.exp_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SRemove _sremove)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_sremove.ident_, 0);
       render(".");
       render("remove");
       render("[");
       pp(_sremove.exp_, 0);
       render("]");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SSet _sset)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_sset.ident_, 0);
       render(".");
       render("set");
       render("(");
       pp(_sset.exp_1, 0);
       render(",");
       pp(_sset.exp_2, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SReturn _sreturn)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("return");
       pp(_sreturn.exp_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SObjInit _sobjinit)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("object");
       pp(_sobjinit.ident_1, 0);
       render("=");
       render("new");
       pp(_sobjinit.ident_2, 0);
       render("(");
       pp(_sobjinit.listexp_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.IfS _ifs)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_ifs.if_stm_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.Block _block)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("{");
       pp(_block.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.Item foo, int _i_)
  {
    if (foo instanceof lang.Absyn.LstItem _lstitem)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_lstitem.exp_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.ListItem foo, int _i_)
  {
    ppListItem(foo.iterator(), _i_);
  }

  private static void ppListItem(java.util.Iterator<lang.Absyn.Item> it, int _i_)
  {
    if (it.hasNext())
    {
      lang.Absyn.Item el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListItem(it, _i_);
      }
    }
  }


  private static void pp(lang.Absyn.Stm_Initialise foo, int _i_)
  {
    if (foo instanceof lang.Absyn.SInit _sinit)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_sinit.vartype_, 0);
       pp(_sinit.ident_, 0);
       render("=");
       pp(_sinit.exp_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.Stm_Declare foo, int _i_)
  {
    if (foo instanceof lang.Absyn.SDecl _sdecl)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_sdecl.vartype_, 0);
       pp(_sdecl.ident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.Stm_Assign foo, int _i_)
  {
    if (foo instanceof lang.Absyn.SAssign _sassign)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_sassign.ident_, 0);
       pp(_sassign.assign_op_, 0);
       pp(_sassign.exp_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.Stm_IncrmDecrm foo, int _i_)
  {
    if (foo instanceof lang.Absyn.SIncrmDecrm _sincrmdecrm)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_sincrmdecrm.ident_, 0);
       pp(_sincrmdecrm.incrmdecrm_op_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.Stm_Loop foo, int _i_)
  {
    if (foo instanceof lang.Absyn.SWhile _swhile)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("while");
       pp(_swhile.exp_, 0);
       render("{");
       pp(_swhile.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SPLoopIdent _sploopident)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("repeat");
       pp(_sploopident.ident_1, 0);
       render("in");
       pp(_sploopident.ident_2, 0);
       render("{");
       pp(_sploopident.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SPLoopList _splooplist)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("repeat");
       pp(_splooplist.ident_, 0);
       render("in");
       render("[");
       pp(_splooplist.listitem_, 0);
       render("]");
       render("{");
       pp(_splooplist.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SPLoopRangeStart _splooprangestart)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("repeat");
       pp(_splooprangestart.ident_, 0);
       render("in");
       render("range");
       render("(");
       pp(_splooprangestart.exp_, 0);
       render(")");
       render("{");
       pp(_splooprangestart.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SPLoopRangeStartStop _splooprangestartstop)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("repeat");
       pp(_splooprangestartstop.ident_, 0);
       render("in");
       render("range");
       render("(");
       pp(_splooprangestartstop.exp_1, 0);
       render(",");
       pp(_splooprangestartstop.exp_2, 0);
       render(")");
       render("{");
       pp(_splooprangestartstop.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SPLoopRangeStartStopEnd _splooprangestartstopend)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("repeat");
       pp(_splooprangestartstopend.ident_, 0);
       render("in");
       render("range");
       render("(");
       pp(_splooprangestartstopend.exp_1, 0);
       render(",");
       pp(_splooprangestartstopend.exp_2, 0);
       render(",");
       pp(_splooprangestartstopend.exp_3, 0);
       render(")");
       render("{");
       pp(_splooprangestartstopend.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SCLoop _scloop)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("repeat");
       pp(_scloop.stm_initialise_, 0);
       render(",");
       pp(_scloop.exp_, 0);
       render(",");
       pp(_scloop.stm_incrmdecrm_, 0);
       render("{");
       pp(_scloop.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SCLoopAssign _scloopassign)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("repeat");
       pp(_scloopassign.stm_initialise_, 0);
       render(",");
       pp(_scloopassign.exp_, 0);
       render(",");
       pp(_scloopassign.stm_assign_, 0);
       render("{");
       pp(_scloopassign.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.If_Stm foo, int _i_)
  {
    if (foo instanceof lang.Absyn.SIf _sif)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("if");
       pp(_sif.exp_, 0);
       render("{");
       pp(_sif.liststm_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SIfElse _sifelse)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("if");
       pp(_sifelse.exp_, 0);
       render("{");
       pp(_sifelse.liststm_1, 0);
       render("}");
       render("else");
       render("{");
       pp(_sifelse.liststm_2, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.SIfElseIf _sifelseif)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("if");
       pp(_sifelseif.exp_, 0);
       render("{");
       pp(_sifelseif.liststm_, 0);
       render("}");
       render("else");
       pp(_sifelseif.if_stm_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.Arg foo, int _i_)
  {
    if (foo instanceof lang.Absyn.ArgDecl _argdecl)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_argdecl.vartype_, 0);
       pp(_argdecl.ident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.ListArg foo, int _i_)
  {
    ppListArg(foo.iterator(), _i_);
  }

  private static void ppListArg(java.util.Iterator<lang.Absyn.Arg> it, int _i_)
  {
    if (it.hasNext())
    {
      lang.Absyn.Arg el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListArg(it, _i_);
      }
    }
  }


  private static void pp(lang.Absyn.ListStm foo, int _i_)
  {
    ppListStm(foo.iterator(), _i_);
  }

  private static void ppListStm(java.util.Iterator<lang.Absyn.Stm> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      lang.Absyn.Stm el = it.next();
      pp(el, _i_); render(""); ppListStm(it, _i_);
    }
  }


  private static void pp(lang.Absyn.Exp foo, int _i_)
  {
    if (foo instanceof lang.Absyn.EInt _eint)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_eint.integer_, 0);
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ENegInt _enegint)
    {
        if (_i_ > 15) render(_L_PAREN);
       render("-");
       pp(_enegint.integer_, 0);
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EChar _echar)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_echar.char_, 0);
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EDouble _edouble)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_edouble.double_, 0);
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ENegDouble _enegdouble)
    {
        if (_i_ > 15) render(_L_PAREN);
       render("-");
       pp(_enegdouble.double_, 0);
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EString _estring)
    {
        if (_i_ > 15) render(_L_PAREN);
       printQuoted(_estring.string_);
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ETrue _etrue)
    {
        if (_i_ > 15) render(_L_PAREN);
       render("true");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EFalse _efalse)
    {
        if (_i_ > 15) render(_L_PAREN);
       render("false");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EId _eid)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_eid.ident_, 0);
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EType _etype)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_etype.ident_, 0);
       render(".");
       render("isType");
       render("(");
       pp(_etype.vartype_, 0);
       render(")");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EListItem _elistitem)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_elistitem.ident_, 0);
       render("[");
       pp(_elistitem.exp_, 0);
       render("]");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EListWith _elistwith)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_elistwith.ident_, 0);
       render(".");
       render("with");
       render("(");
       pp(_elistwith.exp_, 0);
       render(")");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EListWithout _elistwithout)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_elistwithout.ident_, 0);
       render(".");
       render("without");
       render("[");
       pp(_elistwithout.exp_, 0);
       render("]");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EList _elist)
    {
        if (_i_ > 15) render(_L_PAREN);
       render("[");
       pp(_elist.listitem_, 0);
       render("]");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EListSize _elistsize)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_elistsize.ident_, 0);
       render(".");
       render("size");
       render("(");
       render(")");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EListIsEmpty _elistisempty)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_elistisempty.ident_, 0);
       render(".");
       render("isEmpty");
       render("(");
       render(")");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EInput _einput)
    {
        if (_i_ > 15) render(_L_PAREN);
       render("input");
       render("(");
       render(")");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EInputString _einputstring)
    {
        if (_i_ > 15) render(_L_PAREN);
       render("input");
       render("(");
       printQuoted(_einputstring.string_);
       render(")");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EStrLength _estrlength)
    {
        if (_i_ > 15) render(_L_PAREN);
       pp(_estrlength.ident_, 0);
       render(".");
       render("length");
       render("(");
       render(")");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ERand _erand)
    {
        if (_i_ > 15) render(_L_PAREN);
       render("randomInt");
       render("(");
       pp(_erand.integer_, 0);
       render(")");
       if (_i_ > 15) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ETypeCast _etypecast)
    {
        if (_i_ > 16) render(_L_PAREN);
       pp(_etypecast.ident_, 0);
       render(".");
       pp(_etypecast.typecast_, 0);
       render("(");
       render(")");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ELambda _elambda)
    {
        if (_i_ > 16) render(_L_PAREN);
       render("lambda");
       render("(");
       pp(_elambda.listarg_, 0);
       render(")");
       render("{");
       pp(_elambda.liststm_, 0);
       render("}");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EMapIdent _emapident)
    {
        if (_i_ > 16) render(_L_PAREN);
       render("map");
       render("(");
       pp(_emapident.exp_, 0);
       render(",");
       pp(_emapident.ident_, 0);
       render(")");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EMapList _emaplist)
    {
        if (_i_ > 16) render(_L_PAREN);
       render("map");
       render("(");
       pp(_emaplist.exp_, 0);
       render(",");
       render("[");
       pp(_emaplist.listitem_, 0);
       render("]");
       render(")");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EFilterIdent _efilterident)
    {
        if (_i_ > 16) render(_L_PAREN);
       render("filter");
       render("(");
       pp(_efilterident.exp_, 0);
       render(",");
       pp(_efilterident.ident_, 0);
       render(")");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EFilterList _efilterlist)
    {
        if (_i_ > 16) render(_L_PAREN);
       render("filter");
       render("(");
       pp(_efilterlist.exp_, 0);
       render(",");
       render("[");
       pp(_efilterlist.listitem_, 0);
       render("]");
       render(")");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EReduceIdent _ereduceident)
    {
        if (_i_ > 16) render(_L_PAREN);
       render("reduce");
       render("(");
       pp(_ereduceident.exp_, 0);
       render(",");
       pp(_ereduceident.ident_, 0);
       render(")");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EReduceList _ereducelist)
    {
        if (_i_ > 16) render(_L_PAREN);
       render("reduce");
       render("(");
       pp(_ereducelist.exp_, 0);
       render(",");
       render("[");
       pp(_ereducelist.listitem_, 0);
       render("]");
       render(")");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ESelect _eselect)
    {
        if (_i_ > 16) render(_L_PAREN);
       pp(_eselect.ident_1, 0);
       render(".");
       pp(_eselect.ident_2, 0);
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ESelectListItem _eselectlistitem)
    {
        if (_i_ > 16) render(_L_PAREN);
       pp(_eselectlistitem.ident_1, 0);
       render(".");
       pp(_eselectlistitem.ident_2, 0);
       render("[");
       pp(_eselectlistitem.exp_, 0);
       render("]");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ECall _ecall)
    {
        if (_i_ > 16) render(_L_PAREN);
       pp(_ecall.ident_, 0);
       render("(");
       pp(_ecall.listexp_, 0);
       render(")");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EObjCall _eobjcall)
    {
        if (_i_ > 16) render(_L_PAREN);
       pp(_eobjcall.ident_1, 0);
       render(".");
       pp(_eobjcall.ident_2, 0);
       render("(");
       pp(_eobjcall.listexp_, 0);
       render(")");
       if (_i_ > 16) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EPow _epow)
    {
        if (_i_ > 13) render(_L_PAREN);
       pp(_epow.exp_1, 13);
       render("**");
       pp(_epow.exp_2, 14);
       if (_i_ > 13) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EMul _emul)
    {
        if (_i_ > 12) render(_L_PAREN);
       pp(_emul.exp_1, 12);
       render("*");
       pp(_emul.exp_2, 13);
       if (_i_ > 12) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EDiv _ediv)
    {
        if (_i_ > 12) render(_L_PAREN);
       pp(_ediv.exp_1, 12);
       render("/");
       pp(_ediv.exp_2, 13);
       if (_i_ > 12) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EMod _emod)
    {
        if (_i_ > 12) render(_L_PAREN);
       pp(_emod.exp_1, 12);
       render("%");
       pp(_emod.exp_2, 13);
       if (_i_ > 12) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EAdd _eadd)
    {
        if (_i_ > 11) render(_L_PAREN);
       pp(_eadd.exp_1, 11);
       render("+");
       pp(_eadd.exp_2, 12);
       if (_i_ > 11) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ESub _esub)
    {
        if (_i_ > 11) render(_L_PAREN);
       pp(_esub.exp_1, 11);
       render("-");
       pp(_esub.exp_2, 12);
       if (_i_ > 11) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ELt _elt)
    {
        if (_i_ > 9) render(_L_PAREN);
       pp(_elt.exp_1, 9);
       render("<");
       pp(_elt.exp_2, 10);
       if (_i_ > 9) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EGt _egt)
    {
        if (_i_ > 9) render(_L_PAREN);
       pp(_egt.exp_1, 9);
       render(">");
       pp(_egt.exp_2, 10);
       if (_i_ > 9) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ELEq _eleq)
    {
        if (_i_ > 9) render(_L_PAREN);
       pp(_eleq.exp_1, 9);
       render("<=");
       pp(_eleq.exp_2, 10);
       if (_i_ > 9) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EGEq _egeq)
    {
        if (_i_ > 9) render(_L_PAREN);
       pp(_egeq.exp_1, 9);
       render(">=");
       pp(_egeq.exp_2, 10);
       if (_i_ > 9) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EEq _eeq)
    {
        if (_i_ > 8) render(_L_PAREN);
       pp(_eeq.exp_1, 8);
       render("==");
       pp(_eeq.exp_2, 9);
       if (_i_ > 8) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.ENEq _eneq)
    {
        if (_i_ > 8) render(_L_PAREN);
       pp(_eneq.exp_1, 8);
       render("!=");
       pp(_eneq.exp_2, 9);
       if (_i_ > 8) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EAnd _eand)
    {
        if (_i_ > 4) render(_L_PAREN);
       pp(_eand.exp_1, 4);
       render("AND");
       pp(_eand.exp_2, 5);
       if (_i_ > 4) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.EOr _eor)
    {
        if (_i_ > 3) render(_L_PAREN);
       pp(_eor.exp_1, 3);
       render("OR");
       pp(_eor.exp_2, 4);
       if (_i_ > 3) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.ListIdent foo, int _i_)
  {
    ppListIdent(foo.iterator(), _i_);
  }

  private static void ppListIdent(java.util.Iterator<String> it, int _i_)
  {
    if (it.hasNext())
    {
      String el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListIdent(it, _i_);
      }
    }
  }


  private static void pp(lang.Absyn.Assign_Op foo, int _i_)
  {
    if (foo instanceof lang.Absyn.Assign _assign)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("=");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.AssignMul _assignmul)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("*=");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.AssignDiv _assigndiv)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("/=");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.AssignMod _assignmod)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("%=");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.AssignAdd _assignadd)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("+=");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.AssignSub _assignsub)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("-=");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.IncrmDecrm_Op foo, int _i_)
  {
    if (foo instanceof lang.Absyn.Increment _increment)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("++");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.Decrement _decrement)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("--");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.ListExp foo, int _i_)
  {
    ppListExp(foo.iterator(), _i_);
  }

  private static void ppListExp(java.util.Iterator<lang.Absyn.Exp> it, int _i_)
  {
    if (it.hasNext())
    {
      lang.Absyn.Exp el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListExp(it, _i_);
      }
    }
  }


  private static void pp(lang.Absyn.FuncType foo, int _i_)
  {
    if (foo instanceof lang.Absyn.FuncType_void _functype_void)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("void");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.FuncTypeVarType _functypevartype)
    {
        if (_i_ > 0) render(_L_PAREN);
       pp(_functypevartype.vartype_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.VarType foo, int _i_)
  {
    if (foo instanceof lang.Absyn.VarType_int _vartype_int)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("int");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.VarType_double _vartype_double)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("double");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.VarType_bool _vartype_bool)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("bool");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.VarType_char _vartype_char)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("char");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.VarType_string _vartype_string)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("string");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.VarType_auto _vartype_auto)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("auto");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.VarType_func _vartype_func)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("func");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.VarType_object _vartype_object)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("object");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(lang.Absyn.TypeCast foo, int _i_)
  {
    if (foo instanceof lang.Absyn.TypeCast_toInt _typecast_toint)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("toInt");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.TypeCast_toDouble _typecast_todouble)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("toDouble");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.TypeCast_toBool _typecast_tobool)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("toBool");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.TypeCast_toChar _typecast_tochar)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("toChar");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof lang.Absyn.TypeCast_toString _typecast_tostring)
    {
        if (_i_ > 0) render(_L_PAREN);
       render("toString");
       if (_i_ > 0) render(_R_PAREN);
    }

  }


  private static void sh(lang.Absyn.Program foo)
  {
    if (foo instanceof lang.Absyn.PStms _pstms)
    {
        render("(");
       render("PStms");
       render("[");
       sh(_pstms.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.PFunctionalModeStms _pfunctionalmodestms)
    {
        render("(");
       render("PFunctionalModeStms");
       render("[");
       sh(_pfunctionalmodestms.liststm_);
       render("]");
       render(")");
    }
  }

  private static void sh(lang.Absyn.Stm foo)
  {
    if (foo instanceof lang.Absyn.DefFun _deffun)
    {
        render("(");
       render("DefFun");
       sh(_deffun.functype_);
       sh(_deffun.ident_);
       render("[");
       sh(_deffun.listarg_);
       render("]");
       render("[");
       sh(_deffun.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.DefConstructor _defconstructor)
    {
        render("(");
       render("DefConstructor");
       sh(_defconstructor.ident_);
       render("[");
       sh(_defconstructor.listarg_);
       render("]");
       render("[");
       sh(_defconstructor.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.DefClass _defclass)
    {
        render("(");
       render("DefClass");
       sh(_defclass.ident_);
       render("[");
       sh(_defclass.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.DefClassInherits _defclassinherits)
    {
        render("(");
       render("DefClassInherits");
       sh(_defclassinherits.ident_1);
       sh(_defclassinherits.ident_2);
       render("[");
       sh(_defclassinherits.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.STryCatch _strycatch)
    {
        render("(");
       render("STryCatch");
       render("[");
       sh(_strycatch.liststm_1);
       render("]");
       sh(_strycatch.ident_);
       render("[");
       sh(_strycatch.liststm_2);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.STryCatchFinally _strycatchfinally)
    {
        render("(");
       render("STryCatchFinally");
       render("[");
       sh(_strycatchfinally.liststm_1);
       render("]");
       sh(_strycatchfinally.ident_);
       render("[");
       sh(_strycatchfinally.liststm_2);
       render("]");
       render("[");
       sh(_strycatchfinally.liststm_3);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.SPrint _sprint)
    {
        render("(");
       render("SPrint");
       sh(_sprint.exp_);
       render(")");
    }
    if (foo instanceof lang.Absyn.SBreak _sbreak)
    {
        render("SBreak");
    }
    if (foo instanceof lang.Absyn.SContinue _scontinue)
    {
        render("SContinue");
    }
    if (foo instanceof lang.Absyn.SThrow _sthrow)
    {
        render("(");
       render("SThrow");
       sh(_sthrow.exp_);
       render(")");
    }
    if (foo instanceof lang.Absyn.InitialiseStm _initialisestm)
    {
        render("(");
       render("InitialiseStm");
       sh(_initialisestm.stm_initialise_);
       render(")");
    }
    if (foo instanceof lang.Absyn.DeclareStm _declarestm)
    {
        render("(");
       render("DeclareStm");
       sh(_declarestm.stm_declare_);
       render(")");
    }
    if (foo instanceof lang.Absyn.AssignStm _assignstm)
    {
        render("(");
       render("AssignStm");
       sh(_assignstm.stm_assign_);
       render(")");
    }
    if (foo instanceof lang.Absyn.LoopStm _loopstm)
    {
        render("(");
       render("LoopStm");
       sh(_loopstm.stm_loop_);
       render(")");
    }
    if (foo instanceof lang.Absyn.IncrnDecrmStm _incrndecrmstm)
    {
        render("(");
       render("IncrnDecrmStm");
       sh(_incrndecrmstm.stm_incrmdecrm_);
       render(")");
    }
    if (foo instanceof lang.Absyn.SCall _scall)
    {
        render("(");
       render("SCall");
       sh(_scall.exp_);
       render(")");
    }
    if (foo instanceof lang.Absyn.SAppend _sappend)
    {
        render("(");
       render("SAppend");
       sh(_sappend.ident_);
       sh(_sappend.exp_);
       render(")");
    }
    if (foo instanceof lang.Absyn.SRemove _sremove)
    {
        render("(");
       render("SRemove");
       sh(_sremove.ident_);
       sh(_sremove.exp_);
       render(")");
    }
    if (foo instanceof lang.Absyn.SSet _sset)
    {
        render("(");
       render("SSet");
       sh(_sset.ident_);
       sh(_sset.exp_1);
       sh(_sset.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.SReturn _sreturn)
    {
        render("(");
       render("SReturn");
       sh(_sreturn.exp_);
       render(")");
    }
    if (foo instanceof lang.Absyn.SObjInit _sobjinit)
    {
        render("(");
       render("SObjInit");
       sh(_sobjinit.ident_1);
       sh(_sobjinit.ident_2);
       render("[");
       sh(_sobjinit.listexp_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.IfS _ifs)
    {
        render("(");
       render("IfS");
       sh(_ifs.if_stm_);
       render(")");
    }
    if (foo instanceof lang.Absyn.Block _block)
    {
        render("(");
       render("Block");
       render("[");
       sh(_block.liststm_);
       render("]");
       render(")");
    }
  }

  private static void sh(lang.Absyn.Item foo)
  {
    if (foo instanceof lang.Absyn.LstItem _lstitem)
    {
        render("(");
       render("LstItem");
       sh(_lstitem.exp_);
       render(")");
    }
  }

  private static void sh(lang.Absyn.ListItem foo)
  {
     for (java.util.Iterator<lang.Absyn.Item> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(lang.Absyn.Stm_Initialise foo)
  {
    if (foo instanceof lang.Absyn.SInit _sinit)
    {
        render("(");
       render("SInit");
       sh(_sinit.vartype_);
       sh(_sinit.ident_);
       sh(_sinit.exp_);
       render(")");
    }
  }

  private static void sh(lang.Absyn.Stm_Declare foo)
  {
    if (foo instanceof lang.Absyn.SDecl _sdecl)
    {
        render("(");
       render("SDecl");
       sh(_sdecl.vartype_);
       sh(_sdecl.ident_);
       render(")");
    }
  }

  private static void sh(lang.Absyn.Stm_Assign foo)
  {
    if (foo instanceof lang.Absyn.SAssign _sassign)
    {
        render("(");
       render("SAssign");
       sh(_sassign.ident_);
       sh(_sassign.assign_op_);
       sh(_sassign.exp_);
       render(")");
    }
  }

  private static void sh(lang.Absyn.Stm_IncrmDecrm foo)
  {
    if (foo instanceof lang.Absyn.SIncrmDecrm _sincrmdecrm)
    {
        render("(");
       render("SIncrmDecrm");
       sh(_sincrmdecrm.ident_);
       sh(_sincrmdecrm.incrmdecrm_op_);
       render(")");
    }
  }

  private static void sh(lang.Absyn.Stm_Loop foo)
  {
    if (foo instanceof lang.Absyn.SWhile _swhile)
    {
        render("(");
       render("SWhile");
       sh(_swhile.exp_);
       render("[");
       sh(_swhile.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.SPLoopIdent _sploopident)
    {
        render("(");
       render("SPLoopIdent");
       sh(_sploopident.ident_1);
       sh(_sploopident.ident_2);
       render("[");
       sh(_sploopident.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.SPLoopList _splooplist)
    {
        render("(");
       render("SPLoopList");
       sh(_splooplist.ident_);
       render("[");
       sh(_splooplist.listitem_);
       render("]");
       render("[");
       sh(_splooplist.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.SPLoopRangeStart _splooprangestart)
    {
        render("(");
       render("SPLoopRangeStart");
       sh(_splooprangestart.ident_);
       sh(_splooprangestart.exp_);
       render("[");
       sh(_splooprangestart.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.SPLoopRangeStartStop _splooprangestartstop)
    {
        render("(");
       render("SPLoopRangeStartStop");
       sh(_splooprangestartstop.ident_);
       sh(_splooprangestartstop.exp_1);
       sh(_splooprangestartstop.exp_2);
       render("[");
       sh(_splooprangestartstop.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.SPLoopRangeStartStopEnd _splooprangestartstopend)
    {
        render("(");
       render("SPLoopRangeStartStopEnd");
       sh(_splooprangestartstopend.ident_);
       sh(_splooprangestartstopend.exp_1);
       sh(_splooprangestartstopend.exp_2);
       sh(_splooprangestartstopend.exp_3);
       render("[");
       sh(_splooprangestartstopend.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.SCLoop _scloop)
    {
        render("(");
       render("SCLoop");
       sh(_scloop.stm_initialise_);
       sh(_scloop.exp_);
       sh(_scloop.stm_incrmdecrm_);
       render("[");
       sh(_scloop.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.SCLoopAssign _scloopassign)
    {
        render("(");
       render("SCLoopAssign");
       sh(_scloopassign.stm_initialise_);
       sh(_scloopassign.exp_);
       sh(_scloopassign.stm_assign_);
       render("[");
       sh(_scloopassign.liststm_);
       render("]");
       render(")");
    }
  }

  private static void sh(lang.Absyn.If_Stm foo)
  {
    if (foo instanceof lang.Absyn.SIf _sif)
    {
        render("(");
       render("SIf");
       sh(_sif.exp_);
       render("[");
       sh(_sif.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.SIfElse _sifelse)
    {
        render("(");
       render("SIfElse");
       sh(_sifelse.exp_);
       render("[");
       sh(_sifelse.liststm_1);
       render("]");
       render("[");
       sh(_sifelse.liststm_2);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.SIfElseIf _sifelseif)
    {
        render("(");
       render("SIfElseIf");
       sh(_sifelseif.exp_);
       render("[");
       sh(_sifelseif.liststm_);
       render("]");
       sh(_sifelseif.if_stm_);
       render(")");
    }
  }

  private static void sh(lang.Absyn.Arg foo)
  {
    if (foo instanceof lang.Absyn.ArgDecl _argdecl)
    {
        render("(");
       render("ArgDecl");
       sh(_argdecl.vartype_);
       sh(_argdecl.ident_);
       render(")");
    }
  }

  private static void sh(lang.Absyn.ListArg foo)
  {
     for (java.util.Iterator<lang.Absyn.Arg> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(lang.Absyn.ListStm foo)
  {
     for (java.util.Iterator<lang.Absyn.Stm> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(lang.Absyn.Exp foo)
  {
    if (foo instanceof lang.Absyn.EInt _eint)
    {
        render("(");
       render("EInt");
       sh(_eint.integer_);
       render(")");
    }
    if (foo instanceof lang.Absyn.ENegInt _enegint)
    {
        render("(");
       render("ENegInt");
       sh(_enegint.integer_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EChar _echar)
    {
        render("(");
       render("EChar");
       sh(_echar.char_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EDouble _edouble)
    {
        render("(");
       render("EDouble");
       sh(_edouble.double_);
       render(")");
    }
    if (foo instanceof lang.Absyn.ENegDouble _enegdouble)
    {
        render("(");
       render("ENegDouble");
       sh(_enegdouble.double_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EString _estring)
    {
        render("(");
       render("EString");
       sh(_estring.string_);
       render(")");
    }
    if (foo instanceof lang.Absyn.ETrue _etrue)
    {
        render("ETrue");
    }
    if (foo instanceof lang.Absyn.EFalse _efalse)
    {
        render("EFalse");
    }
    if (foo instanceof lang.Absyn.EId _eid)
    {
        render("(");
       render("EId");
       sh(_eid.ident_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EType _etype)
    {
        render("(");
       render("EType");
       sh(_etype.ident_);
       sh(_etype.vartype_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EListItem _elistitem)
    {
        render("(");
       render("EListItem");
       sh(_elistitem.ident_);
       sh(_elistitem.exp_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EListWith _elistwith)
    {
        render("(");
       render("EListWith");
       sh(_elistwith.ident_);
       sh(_elistwith.exp_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EListWithout _elistwithout)
    {
        render("(");
       render("EListWithout");
       sh(_elistwithout.ident_);
       sh(_elistwithout.exp_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EList _elist)
    {
        render("(");
       render("EList");
       render("[");
       sh(_elist.listitem_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.EListSize _elistsize)
    {
        render("(");
       render("EListSize");
       sh(_elistsize.ident_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EListIsEmpty _elistisempty)
    {
        render("(");
       render("EListIsEmpty");
       sh(_elistisempty.ident_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EInput _einput)
    {
        render("EInput");
    }
    if (foo instanceof lang.Absyn.EInputString _einputstring)
    {
        render("(");
       render("EInputString");
       sh(_einputstring.string_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EStrLength _estrlength)
    {
        render("(");
       render("EStrLength");
       sh(_estrlength.ident_);
       render(")");
    }
    if (foo instanceof lang.Absyn.ERand _erand)
    {
        render("(");
       render("ERand");
       sh(_erand.integer_);
       render(")");
    }
    if (foo instanceof lang.Absyn.ETypeCast _etypecast)
    {
        render("(");
       render("ETypeCast");
       sh(_etypecast.ident_);
       sh(_etypecast.typecast_);
       render(")");
    }
    if (foo instanceof lang.Absyn.ELambda _elambda)
    {
        render("(");
       render("ELambda");
       render("[");
       sh(_elambda.listarg_);
       render("]");
       render("[");
       sh(_elambda.liststm_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.EMapIdent _emapident)
    {
        render("(");
       render("EMapIdent");
       sh(_emapident.exp_);
       sh(_emapident.ident_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EMapList _emaplist)
    {
        render("(");
       render("EMapList");
       sh(_emaplist.exp_);
       render("[");
       sh(_emaplist.listitem_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.EFilterIdent _efilterident)
    {
        render("(");
       render("EFilterIdent");
       sh(_efilterident.exp_);
       sh(_efilterident.ident_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EFilterList _efilterlist)
    {
        render("(");
       render("EFilterList");
       sh(_efilterlist.exp_);
       render("[");
       sh(_efilterlist.listitem_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.EReduceIdent _ereduceident)
    {
        render("(");
       render("EReduceIdent");
       sh(_ereduceident.exp_);
       sh(_ereduceident.ident_);
       render(")");
    }
    if (foo instanceof lang.Absyn.EReduceList _ereducelist)
    {
        render("(");
       render("EReduceList");
       sh(_ereducelist.exp_);
       render("[");
       sh(_ereducelist.listitem_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.ESelect _eselect)
    {
        render("(");
       render("ESelect");
       sh(_eselect.ident_1);
       sh(_eselect.ident_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.ESelectListItem _eselectlistitem)
    {
        render("(");
       render("ESelectListItem");
       sh(_eselectlistitem.ident_1);
       sh(_eselectlistitem.ident_2);
       sh(_eselectlistitem.exp_);
       render(")");
    }
    if (foo instanceof lang.Absyn.ECall _ecall)
    {
        render("(");
       render("ECall");
       sh(_ecall.ident_);
       render("[");
       sh(_ecall.listexp_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.EObjCall _eobjcall)
    {
        render("(");
       render("EObjCall");
       sh(_eobjcall.ident_1);
       sh(_eobjcall.ident_2);
       render("[");
       sh(_eobjcall.listexp_);
       render("]");
       render(")");
    }
    if (foo instanceof lang.Absyn.EPow _epow)
    {
        render("(");
       render("EPow");
       sh(_epow.exp_1);
       sh(_epow.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.EMul _emul)
    {
        render("(");
       render("EMul");
       sh(_emul.exp_1);
       sh(_emul.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.EDiv _ediv)
    {
        render("(");
       render("EDiv");
       sh(_ediv.exp_1);
       sh(_ediv.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.EMod _emod)
    {
        render("(");
       render("EMod");
       sh(_emod.exp_1);
       sh(_emod.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.EAdd _eadd)
    {
        render("(");
       render("EAdd");
       sh(_eadd.exp_1);
       sh(_eadd.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.ESub _esub)
    {
        render("(");
       render("ESub");
       sh(_esub.exp_1);
       sh(_esub.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.ELt _elt)
    {
        render("(");
       render("ELt");
       sh(_elt.exp_1);
       sh(_elt.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.EGt _egt)
    {
        render("(");
       render("EGt");
       sh(_egt.exp_1);
       sh(_egt.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.ELEq _eleq)
    {
        render("(");
       render("ELEq");
       sh(_eleq.exp_1);
       sh(_eleq.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.EGEq _egeq)
    {
        render("(");
       render("EGEq");
       sh(_egeq.exp_1);
       sh(_egeq.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.EEq _eeq)
    {
        render("(");
       render("EEq");
       sh(_eeq.exp_1);
       sh(_eeq.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.ENEq _eneq)
    {
        render("(");
       render("ENEq");
       sh(_eneq.exp_1);
       sh(_eneq.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.EAnd _eand)
    {
        render("(");
       render("EAnd");
       sh(_eand.exp_1);
       sh(_eand.exp_2);
       render(")");
    }
    if (foo instanceof lang.Absyn.EOr _eor)
    {
        render("(");
       render("EOr");
       sh(_eor.exp_1);
       sh(_eor.exp_2);
       render(")");
    }
  }

  private static void sh(lang.Absyn.ListIdent foo)
  {
     for (java.util.Iterator<String> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(lang.Absyn.Assign_Op foo)
  {
    if (foo instanceof lang.Absyn.Assign _assign)
    {
        render("Assign");
    }
    if (foo instanceof lang.Absyn.AssignMul _assignmul)
    {
        render("AssignMul");
    }
    if (foo instanceof lang.Absyn.AssignDiv _assigndiv)
    {
        render("AssignDiv");
    }
    if (foo instanceof lang.Absyn.AssignMod _assignmod)
    {
        render("AssignMod");
    }
    if (foo instanceof lang.Absyn.AssignAdd _assignadd)
    {
        render("AssignAdd");
    }
    if (foo instanceof lang.Absyn.AssignSub _assignsub)
    {
        render("AssignSub");
    }
  }

  private static void sh(lang.Absyn.IncrmDecrm_Op foo)
  {
    if (foo instanceof lang.Absyn.Increment _increment)
    {
        render("Increment");
    }
    if (foo instanceof lang.Absyn.Decrement _decrement)
    {
        render("Decrement");
    }
  }

  private static void sh(lang.Absyn.ListExp foo)
  {
     for (java.util.Iterator<lang.Absyn.Exp> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(lang.Absyn.FuncType foo)
  {
    if (foo instanceof lang.Absyn.FuncType_void _functype_void)
    {
        render("FuncType_void");
    }
    if (foo instanceof lang.Absyn.FuncTypeVarType _functypevartype)
    {
        render("(");
       render("FuncTypeVarType");
       sh(_functypevartype.vartype_);
       render(")");
    }
  }

  private static void sh(lang.Absyn.VarType foo)
  {
    if (foo instanceof lang.Absyn.VarType_int _vartype_int)
    {
        render("VarType_int");
    }
    if (foo instanceof lang.Absyn.VarType_double _vartype_double)
    {
        render("VarType_double");
    }
    if (foo instanceof lang.Absyn.VarType_bool _vartype_bool)
    {
        render("VarType_bool");
    }
    if (foo instanceof lang.Absyn.VarType_char _vartype_char)
    {
        render("VarType_char");
    }
    if (foo instanceof lang.Absyn.VarType_string _vartype_string)
    {
        render("VarType_string");
    }
    if (foo instanceof lang.Absyn.VarType_auto _vartype_auto)
    {
        render("VarType_auto");
    }
    if (foo instanceof lang.Absyn.VarType_func _vartype_func)
    {
        render("VarType_func");
    }
    if (foo instanceof lang.Absyn.VarType_object _vartype_object)
    {
        render("VarType_object");
    }
  }

  private static void sh(lang.Absyn.TypeCast foo)
  {
    if (foo instanceof lang.Absyn.TypeCast_toInt _typecast_toint)
    {
        render("TypeCast_toInt");
    }
    if (foo instanceof lang.Absyn.TypeCast_toDouble _typecast_todouble)
    {
        render("TypeCast_toDouble");
    }
    if (foo instanceof lang.Absyn.TypeCast_toBool _typecast_tobool)
    {
        render("TypeCast_toBool");
    }
    if (foo instanceof lang.Absyn.TypeCast_toChar _typecast_tochar)
    {
        render("TypeCast_toChar");
    }
    if (foo instanceof lang.Absyn.TypeCast_toString _typecast_tostring)
    {
        render("TypeCast_toString");
    }
  }


  private static void pp(Integer n, int _i_) { buf_.append(n); buf_.append(" "); }
  private static void pp(Double d, int _i_) { buf_.append(String.format(java.util.Locale.ROOT, "%.15g ", d)); }
  private static void pp(String s, int _i_) { buf_.append(s); buf_.append(" "); }
  private static void pp(Character c, int _i_) { buf_.append("'" + c.toString() + "'"); buf_.append(" "); }
  private static void sh(Integer n) { render(n.toString()); }
  private static void sh(Double d) { render(String.format(java.util.Locale.ROOT, "%.15g", d)); }
  private static void sh(Character c) { render("'" + c.toString() + "'"); }
  private static void sh(String s) { printQuoted(s); }

  private static void printQuoted(String s) { render("\"" + s + "\""); }

  private static void indent()
  {
    int n = _n_;
    while (n > 0)
    {
      buf_.append(' ');
      n--;
    }
  }

  private static void backup()
  {
    int prev = buf_.length() - 1;
    if (prev >= 0 && buf_.charAt(prev) == ' ')
      buf_.setLength(prev);
  }

  private static void trim()
  {
    // Trim initial spaces
    int end = 0;
    int len = buf_.length();
    while (end < len && buf_.charAt(end) == ' ')
      end++;
    buf_.delete(0, end);
    // Trim trailing spaces
    removeTrailingSpaces();
  }

  private static void removeTrailingSpaces()
  {
    int end = buf_.length();
    while (end > 0 && buf_.charAt(end-1) == ' ')
      end--;
    buf_.setLength(end);
  }

  private static void removeTrailingWhitespace()
  {
    int end = buf_.length();
    while (end > 0 && (buf_.charAt(end-1) == ' ' || buf_.charAt(end-1) == '\n'))
      end--;
    buf_.setLength(end);
  }

  private static void onEmptyLine()
  {
    removeTrailingSpaces();
    int len = buf_.length();
    if (len > 0 && buf_.charAt(len-1) != '\n') buf_.append("\n");
    indent();
  }

  private static int _n_ = 0;
  private static final StringBuilder buf_ = new StringBuilder(INITIAL_BUFFER_SIZE);
}

