// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public abstract class Assign_Op implements java.io.Serializable {
  public abstract <R,A> R accept(Assign_Op.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(lang.Absyn.Assign p, A arg);
    public R visit(lang.Absyn.AssignMul p, A arg);
    public R visit(lang.Absyn.AssignDiv p, A arg);
    public R visit(lang.Absyn.AssignMod p, A arg);
    public R visit(lang.Absyn.AssignAdd p, A arg);
    public R visit(lang.Absyn.AssignSub p, A arg);

  }

}
