// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class AssignStm  extends Stm {
  public final Stm_Assign stm_assign_;
  public int line_num, col_num, offset;
  public AssignStm(Stm_Assign p1) { stm_assign_ = p1; }

  public <R,A> R accept(lang.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof AssignStm x) {
        return this.stm_assign_.equals(x.stm_assign_);
    }
    return false;
  }

  public int hashCode() {
    return this.stm_assign_.hashCode();
  }


}
