// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class Assign  extends Assign_Op {
  public int line_num, col_num, offset;
  public Assign() { }

  public <R,A> R accept(lang.Absyn.Assign_Op.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
      return o instanceof Assign;
  }

  public int hashCode() {
    return 37;
  }


}
