// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class DeclareStm  extends Stm {
  public final Stm_Declare stm_declare_;
  public int line_num, col_num, offset;
  public DeclareStm(Stm_Declare p1) { stm_declare_ = p1; }

  public <R,A> R accept(lang.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.DeclareStm) {
      lang.Absyn.DeclareStm x = (lang.Absyn.DeclareStm)o;
      return this.stm_declare_.equals(x.stm_declare_);
    }
    return false;
  }

  public int hashCode() {
    return this.stm_declare_.hashCode();
  }


}
