// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class DefConstructor  extends Stm {
  public final String ident_;
  public final ListArg listarg_;
  public final ListStm liststm_;
  public int line_num, col_num, offset;
  public DefConstructor(String p1, ListArg p2, ListStm p3) { ident_ = p1; listarg_ = p2; liststm_ = p3; }

  public <R,A> R accept(lang.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof DefConstructor x) {
        return this.ident_.equals(x.ident_) && this.listarg_.equals(x.listarg_) && this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.listarg_.hashCode())+this.liststm_.hashCode();
  }


}
