// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class DefFun  extends Stm {
  public final FuncType functype_;
  public final String ident_;
  public final ListArg listarg_;
  public final ListStm liststm_;
  public int line_num, col_num, offset;
  public DefFun(FuncType p1, String p2, ListArg p3, ListStm p4) { functype_ = p1; ident_ = p2; listarg_ = p3; liststm_ = p4; }

  public <R,A> R accept(lang.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.DefFun) {
      lang.Absyn.DefFun x = (lang.Absyn.DefFun)o;
      return this.functype_.equals(x.functype_) && this.ident_.equals(x.ident_) && this.listarg_.equals(x.listarg_) && this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.functype_.hashCode())+this.ident_.hashCode())+this.listarg_.hashCode())+this.liststm_.hashCode();
  }


}
