// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class ECall  extends Exp {
  public final String ident_;
  public final ListExp listexp_;
  public int line_num, col_num, offset;
  public ECall(String p1, ListExp p2) { ident_ = p1; listexp_ = p2; }

  public <R,A> R accept(lang.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ECall x) {
        return this.ident_.equals(x.ident_) && this.listexp_.equals(x.listexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listexp_.hashCode();
  }


}
