// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class EChar  extends Exp {
  public final Character char_;
  public int line_num, col_num, offset;
  public EChar(Character p1) { char_ = p1; }

  public <R,A> R accept(lang.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.EChar) {
      lang.Absyn.EChar x = (lang.Absyn.EChar)o;
      return this.char_.equals(x.char_);
    }
    return false;
  }

  public int hashCode() {
    return this.char_.hashCode();
  }


}
