// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class EDouble  extends Exp {
  public final Double double_;
  public int line_num, col_num, offset;
  public EDouble(Double p1) { double_ = p1; }

  public <R,A> R accept(lang.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof EDouble x) {
        return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
