// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class EFilterList  extends Exp {
  public final Exp exp_;
  public final ListItem listitem_;
  public int line_num, col_num, offset;
  public EFilterList(Exp p1, ListItem p2) { exp_ = p1; listitem_ = p2; }

  public <R,A> R accept(lang.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.EFilterList) {
      lang.Absyn.EFilterList x = (lang.Absyn.EFilterList)o;
      return this.exp_.equals(x.exp_) && this.listitem_.equals(x.listitem_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.listitem_.hashCode();
  }


}
