// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class EInput  extends Exp {
  public int line_num, col_num, offset;
  public EInput() { }

  public <R,A> R accept(lang.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.EInput) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
