// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class ELambda  extends Exp {
  public final ListArg listarg_;
  public final ListStm liststm_;
  public int line_num, col_num, offset;
  public ELambda(ListArg p1, ListStm p2) { listarg_ = p1; liststm_ = p2; }

  public <R,A> R accept(lang.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof ELambda x) {
        return this.listarg_.equals(x.listarg_) && this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listarg_.hashCode())+this.liststm_.hashCode();
  }


}
