// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class EType  extends Exp {
  public final String ident_;
  public final VarType vartype_;
  public int line_num, col_num, offset;
  public EType(String p1, VarType p2) { ident_ = p1; vartype_ = p2; }

  public <R,A> R accept(lang.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof EType x) {
        return this.ident_.equals(x.ident_) && this.vartype_.equals(x.vartype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.vartype_.hashCode();
  }


}
