// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class ETypeCast  extends Exp {
  public final String ident_;
  public final TypeCast typecast_;
  public int line_num, col_num, offset;
  public ETypeCast(String p1, TypeCast p2) { ident_ = p1; typecast_ = p2; }

  public <R,A> R accept(lang.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.ETypeCast) {
      lang.Absyn.ETypeCast x = (lang.Absyn.ETypeCast)o;
      return this.ident_.equals(x.ident_) && this.typecast_.equals(x.typecast_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.typecast_.hashCode();
  }


}
