// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(lang.Absyn.EInt p, A arg);
    public R visit(lang.Absyn.ENegInt p, A arg);
    public R visit(lang.Absyn.EChar p, A arg);
    public R visit(lang.Absyn.EDouble p, A arg);
    public R visit(lang.Absyn.ENegDouble p, A arg);
    public R visit(lang.Absyn.EString p, A arg);
    public R visit(lang.Absyn.ETrue p, A arg);
    public R visit(lang.Absyn.EFalse p, A arg);
    public R visit(lang.Absyn.EId p, A arg);
    public R visit(lang.Absyn.EListItem p, A arg);
    public R visit(lang.Absyn.EList p, A arg);
    public R visit(lang.Absyn.EListSize p, A arg);
    public R visit(lang.Absyn.EInput p, A arg);
    public R visit(lang.Absyn.ETypeCast p, A arg);
    public R visit(lang.Absyn.ELambda p, A arg);
    public R visit(lang.Absyn.EMapIdent p, A arg);
    public R visit(lang.Absyn.EMapList p, A arg);
    public R visit(lang.Absyn.EFilterIdent p, A arg);
    public R visit(lang.Absyn.EFilterList p, A arg);
    public R visit(lang.Absyn.EReduceIdent p, A arg);
    public R visit(lang.Absyn.EReduceList p, A arg);
    public R visit(lang.Absyn.ESelect p, A arg);
    public R visit(lang.Absyn.ESelectListItem p, A arg);
    public R visit(lang.Absyn.ECall p, A arg);
    public R visit(lang.Absyn.EObjCall p, A arg);
    public R visit(lang.Absyn.EPow p, A arg);
    public R visit(lang.Absyn.EMul p, A arg);
    public R visit(lang.Absyn.EDiv p, A arg);
    public R visit(lang.Absyn.EAdd p, A arg);
    public R visit(lang.Absyn.ESub p, A arg);
    public R visit(lang.Absyn.ELt p, A arg);
    public R visit(lang.Absyn.EGt p, A arg);
    public R visit(lang.Absyn.ELEq p, A arg);
    public R visit(lang.Absyn.EGEq p, A arg);
    public R visit(lang.Absyn.EEq p, A arg);
    public R visit(lang.Absyn.ENEq p, A arg);
    public R visit(lang.Absyn.EAnd p, A arg);
    public R visit(lang.Absyn.EOr p, A arg);
    public R visit(lang.Absyn.EAssign p, A arg);

  }

}
