// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class FuncTypeVarType  extends FuncType {
  public final VarType vartype_;
  public int line_num, col_num, offset;
  public FuncTypeVarType(VarType p1) { vartype_ = p1; }

  public <R,A> R accept(lang.Absyn.FuncType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.FuncTypeVarType) {
      lang.Absyn.FuncTypeVarType x = (lang.Absyn.FuncTypeVarType)o;
      return this.vartype_.equals(x.vartype_);
    }
    return false;
  }

  public int hashCode() {
    return this.vartype_.hashCode();
  }


}
