// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class FuncType_void  extends FuncType {
  public int line_num, col_num, offset;
  public FuncType_void() { }

  public <R,A> R accept(lang.Absyn.FuncType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
      return o instanceof FuncType_void;
  }

  public int hashCode() {
    return 37;
  }


}
