// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class Increment  extends IncrmDecrm_Op {
  public int line_num, col_num, offset;
  public Increment() { }

  public <R,A> R accept(lang.Absyn.IncrmDecrm_Op.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.Increment) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
