// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class IncrnDecrmStm  extends Stm {
  public final Stm_IncrmDecrm stm_incrmdecrm_;
  public int line_num, col_num, offset;
  public IncrnDecrmStm(Stm_IncrmDecrm p1) { stm_incrmdecrm_ = p1; }

  public <R,A> R accept(lang.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.IncrnDecrmStm) {
      lang.Absyn.IncrnDecrmStm x = (lang.Absyn.IncrnDecrmStm)o;
      return this.stm_incrmdecrm_.equals(x.stm_incrmdecrm_);
    }
    return false;
  }

  public int hashCode() {
    return this.stm_incrmdecrm_.hashCode();
  }


}
