// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class InitialiseStm  extends Stm {
  public final Stm_Initialise stm_initialise_;
  public int line_num, col_num, offset;
  public InitialiseStm(Stm_Initialise p1) { stm_initialise_ = p1; }

  public <R,A> R accept(lang.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof InitialiseStm x) {
        return this.stm_initialise_.equals(x.stm_initialise_);
    }
    return false;
  }

  public int hashCode() {
    return this.stm_initialise_.hashCode();
  }


}
