// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class LoopStm  extends Stm {
  public final Stm_Loop stm_loop_;
  public int line_num, col_num, offset;
  public LoopStm(Stm_Loop p1) { stm_loop_ = p1; }

  public <R,A> R accept(lang.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof LoopStm x) {
        return this.stm_loop_.equals(x.stm_loop_);
    }
    return false;
  }

  public int hashCode() {
    return this.stm_loop_.hashCode();
  }


}
