// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public abstract class Program implements java.io.Serializable {
  public abstract <R,A> R accept(Program.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    R visit(lang.Absyn.PStms p, A arg);
    R visit(lang.Absyn.PFunctionalModeStms p, A arg);

  }

}
