// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class SAssign  extends Stm_Assign {
  public final String ident_;
  public final Assign_Op assign_op_;
  public final Exp exp_;
  public int line_num, col_num, offset;
  public SAssign(String p1, Assign_Op p2, Exp p3) { ident_ = p1; assign_op_ = p2; exp_ = p3; }

  public <R,A> R accept(lang.Absyn.Stm_Assign.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof SAssign x) {
        return this.ident_.equals(x.ident_) && this.assign_op_.equals(x.assign_op_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.assign_op_.hashCode())+this.exp_.hashCode();
  }


}
