// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class SCLoop  extends Stm_Loop {
  public final Stm_Initialise stm_initialise_;
  public final Exp exp_;
  public final Stm_IncrmDecrm stm_incrmdecrm_;
  public final ListStm liststm_;
  public int line_num, col_num, offset;
  public SCLoop(Stm_Initialise p1, Exp p2, Stm_IncrmDecrm p3, ListStm p4) { stm_initialise_ = p1; exp_ = p2; stm_incrmdecrm_ = p3; liststm_ = p4; }

  public <R,A> R accept(lang.Absyn.Stm_Loop.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof SCLoop x) {
        return this.stm_initialise_.equals(x.stm_initialise_) && this.exp_.equals(x.exp_) && this.stm_incrmdecrm_.equals(x.stm_incrmdecrm_) && this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.stm_initialise_.hashCode())+this.exp_.hashCode())+this.stm_incrmdecrm_.hashCode())+this.liststm_.hashCode();
  }


}
