// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class SIfElse  extends If_Stm {
  public final Exp exp_;
  public final ListStm liststm_1, liststm_2;
  public int line_num, col_num, offset;
  public SIfElse(Exp p1, ListStm p2, ListStm p3) { exp_ = p1; liststm_1 = p2; liststm_2 = p3; }

  public <R,A> R accept(lang.Absyn.If_Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof SIfElse x) {
        return this.exp_.equals(x.exp_) && this.liststm_1.equals(x.liststm_1) && this.liststm_2.equals(x.liststm_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.exp_.hashCode())+this.liststm_1.hashCode())+this.liststm_2.hashCode();
  }


}
