// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class SIfElseIf  extends If_Stm {
  public final Exp exp_;
  public final ListStm liststm_;
  public final If_Stm if_stm_;
  public int line_num, col_num, offset;
  public SIfElseIf(Exp p1, ListStm p2, If_Stm p3) { exp_ = p1; liststm_ = p2; if_stm_ = p3; }

  public <R,A> R accept(lang.Absyn.If_Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.SIfElseIf) {
      lang.Absyn.SIfElseIf x = (lang.Absyn.SIfElseIf)o;
      return this.exp_.equals(x.exp_) && this.liststm_.equals(x.liststm_) && this.if_stm_.equals(x.if_stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.exp_.hashCode())+this.liststm_.hashCode())+this.if_stm_.hashCode();
  }


}
