// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class SIncrmDecrm  extends Stm_IncrmDecrm {
  public final String ident_;
  public final IncrmDecrm_Op incrmdecrm_op_;
  public int line_num, col_num, offset;
  public SIncrmDecrm(String p1, IncrmDecrm_Op p2) { ident_ = p1; incrmdecrm_op_ = p2; }

  public <R,A> R accept(lang.Absyn.Stm_IncrmDecrm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof SIncrmDecrm x) {
        return this.ident_.equals(x.ident_) && this.incrmdecrm_op_.equals(x.incrmdecrm_op_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.incrmdecrm_op_.hashCode();
  }


}
