// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class SPLoopList  extends Stm_Loop {
  public final String ident_;
  public final ListItem listitem_;
  public final ListStm liststm_;
  public int line_num, col_num, offset;
  public SPLoopList(String p1, ListItem p2, ListStm p3) { ident_ = p1; listitem_ = p2; liststm_ = p3; }

  public <R,A> R accept(lang.Absyn.Stm_Loop.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lang.Absyn.SPLoopList) {
      lang.Absyn.SPLoopList x = (lang.Absyn.SPLoopList)o;
      return this.ident_.equals(x.ident_) && this.listitem_.equals(x.listitem_) && this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.listitem_.hashCode())+this.liststm_.hashCode();
  }


}
