// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class STryCatchFinally  extends Stm {
  public final ListStm liststm_1, liststm_2, liststm_3;
  public final String ident_;
  public int line_num, col_num, offset;
  public STryCatchFinally(ListStm p1, String p2, ListStm p3, ListStm p4) { liststm_1 = p1; ident_ = p2; liststm_2 = p3; liststm_3 = p4; }

  public <R,A> R accept(lang.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof STryCatchFinally x) {
        return this.liststm_1.equals(x.liststm_1) && this.ident_.equals(x.ident_) && this.liststm_2.equals(x.liststm_2) && this.liststm_3.equals(x.liststm_3);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.liststm_1.hashCode())+this.ident_.hashCode())+this.liststm_2.hashCode())+this.liststm_3.hashCode();
  }


}
