// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class SWhile  extends Stm_Loop {
  public final Exp exp_;
  public final ListStm liststm_;
  public int line_num, col_num, offset;
  public SWhile(Exp p1, ListStm p2) { exp_ = p1; liststm_ = p2; }

  public <R,A> R accept(lang.Absyn.Stm_Loop.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof SWhile x) {
        return this.exp_.equals(x.exp_) && this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.liststm_.hashCode();
  }


}
