// File generated by the BNF Converter (bnfc 2.9.4.1).

package lang.Absyn;

public class TypeCast_toInt  extends TypeCast {
  public int line_num, col_num, offset;
  public TypeCast_toInt() { }

  public <R,A> R accept(lang.Absyn.TypeCast.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
      return o instanceof TypeCast_toInt;
  }

  public int hashCode() {
    return 37;
  }


}
